name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 68.233.113.104
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |

            docker pull bharath33/docker-ui:latest
            docker stop docker-ui || true
            docker rm docker-ui || true
            docker run -d -p 3000:3000 --name docker-ui bharath33/docker-ui:latest
