name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 68.233.113.104
          username: ubuntu
          key: "-----BEGIN RSA PRIVATE KEY-----MIIEogIBAAKCAQEApUv9w+T+m8lFs7e4e70BqTP++JUQhJnUjt/xtv+BCsfC/oWP49Y5H/Mdl9jgr5rSUzLFWMOs/WlniuhaDn3MacbpZiGrU3RBCs+jWjB4QZQkT//9lvz/RAYGat++UfU9qV3hBtODPC62W5NRex22sZKqMBSSK8ofjJmw8091dV56VC9wwDmZISSbgPUiz4fill8ALU8BFruj3t//T6D1hne6McGwsbiAiyXiSfrw9aiQRcNLuW/ZXClIMCA1DZY3tfoTRHLe6BZl6Ul8TyBXNjg9IU63Koxv6CRA0APlMYwNPxPMwR8Duifd0kMzl6D4G2XxqtrHyGr6jeOj51MxRwIDAQABAoIBAAsrgXCAGacpXhPGRynaxzFJ7uGZdnj0yY+ww8LGrU+vLsFzARriWmXgUJBMUD1NobI27MMSJgR8ikoGvYnb0mPA1KYu1vGtb3UYPEUB9X5o+7M0QfdhYqvpbvxAi7nkxU/xT3Ld+YZS7xvCbsUlEuLDsyB1+L1gy+pSZcoWBS1IeHberXRCFahmpiOcZeqlyBuZddnCnKIP4iLFtCmgHi/FtFkSEhlvd8rPxBVGsa+1pOLYBuovQyCnAJHv/qsFVsNV1W8in0XibQtKa6Nz1UC3AQvS3+Baxb60lJNNnKgv8Z6prcpxsl437Eq6ic3CmUq77q2+1rSu1BfpXY36HDECgYEA6ALYUHjsweALpEexATLr3CCnGJ2Q9XhLdb7FkBPjZOXVcRR6U2eR7pspx/hbvkkKGpNeXCyK3V7YbNRLKRmy7r2HeIaT0BXI7oupZV4DZopTGTEqjoq0srOHpZHirRzucJjhgGhaQ78kFS2RJ8fwgCm/OwdXrogAQ2yDdneamCMCgYEAtmNFYWPh8dENpKmve830OxktjPfNtQa6PInvQf3LricsFhXbAiPevlquITH6DPZDUwYot3eSyVtqTC2/ghYbrUgHvGfG3ykkt70SzGtESLJG/8f9j+i3hD1hG87m1o4z/mHLr+FVhjgAcKoohBsfAiMPzHgb6NapBeU2ZVpQYo0CgYAM/gvLBdqMSNWeD320CXv3ycRRtpEljeT75QD/Pn3fapd3S6RGA2jCqeG/FwNcNo7gShxgoQXtu5/3CDRlStEgWXC6qR6h6nZkFWIZERizp09b+8rcTJwt3avc87xz4Ujg+U63eCCF5rBIl1KnnaS0KKJS1ehtF6ScIfmCqtP3bQKBgGDfX0V4INUonV99RRiz7mnJWLlMETV6akanWK4rWBia876TQyzi0nc2gNBe1Bo4Xs/lMJEp8IwEgvQNRG+awH6MCJfYYve6yabRxP9QZgdasX0/wvzBtV+GnmJ/xXnmM9WEKgSz4ZIVgp5UsopgQVsINmb60JAeG85mzTqN+q4tAoGASwDIrN7qsVEYQ95L7oKmpnoWf7LVPpWBXuM3tCnNPkk4XHLJSs3l30TbyZnLGdm5QrjU89bG+Luu9BwUl1fraiTCiHGyHk+6LOh6TxIkyYJpnJ++gSnPR/xQYYJNOWe9zyRwq5sijYDZG68gMIuXENxVh3F1j0rQN6EeGIjPIBU=-----END RSA PRIVATE KEY-----"
          script: |

            docker pull bharath33/docker-ui:latest
            docker stop docker-ui || true
            docker rm docker-ui || true
            docker run -d -p 3000:3000 --name docker-ui bharath33/docker-ui:latest
